### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Vaib215** [Vaib215/snippets#15]
v4 Add react native support
 - [ ] Add Preview Image ❎
 - [ ] & Pagination
 - [ ] v5 Discovery
 - [ ] v6 Playground
 - [ ] v7 ecommerce for components

Ideas Dump
- [ ] Collections of components
- [ ] Templates

**Comment by Vaib215** [comment]
[ ] CLI to add it to code `npx shadcn add ...`
